# Generated by Django 4.2.2 on 2023-07-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('task', models.CharField(max_length=300)),
                ('id_done', models.BooleanField()),
            ],
        ),
    ]
