# Generated by Django 4.2.2 on 2023-07-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
