# Generated by Django 4.2.2 on 2023-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tasks_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
